name: web_responsive_ui
description: Web responsive con flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_background: ^2.0.0
  animated_text_kit: ^4.2.1
  firebase_core: ^1.21.0
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter         # Add this line
  flutter_svg: ^1.0.0
  flutter_widget_from_html_core: any
  fwfh_webview: ^0.6.2
  google_fonts: ^2.1.0
  intl: ^0.17.0-nullsafety.2
  provider: ^6.0.5
  universal_html: ^2.0.8
  url_launcher: ^6.0.18

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  generate: true # Add this line
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/svg/
    - assets/png/
    - assets/icon/
    - assets/png/store/

    
  fonts:
    - family: Agustina
      fonts:
        - asset: assets/fonts/Agustina.ttf
