name: web_responsive_ui
description: Web responsive con flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  avatar_view: ^1.0.1
  flutter:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/works/
    - assets/img/
    - assets/svg/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf
