name: web_responsive_ui
description: Web responsive con flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animate_do: ^2.0.0
  animated_splash_screen: ^1.1.0
  avatar_view: ^1.0.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_test:
    sdk: flutter
  google_fonts: ^2.1.0
  lottie: ^1.1.0
  provider: ^5.0.0
  responsive_framework: ^0.1.4
  universal_html: ^2.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/works/
    - assets/img/
    - assets/images/
    - assets/svg/
    - assets/json/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf
    - family: Agustina
      fonts:
        - asset: assets/fonts/Agustina.ttf
