name: web_responsive_ui
description: Web responsive con flutter

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  after_layout: ^1.1.0
  animate_do: ^2.0.0
  animated_splash_screen: ^1.1.0
  animated_text_kit: ^4.2.1
  avatar_view: ^1.0.1
  fluro: ^2.0.3
  flutter:
    sdk: flutter
  flutter_staggered_animations: ^1.0.0
  flutter_svg: ^0.22.0
  flutter_test:
    sdk: flutter
  font_awesome_flutter: ^9.1.0
  google_fonts: ^2.1.0
  lottie: ^1.1.0
  provider: ^5.0.0
  responsive_builder: ^0.4.1
  responsive_framework: ^0.1.4
  universal_html: ^2.0.8
  url_launcher: ^6.0.9

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/img/
    - assets/images/
    - assets/svg/
    - assets/json/
    - assets/logo/
  fonts:
    - family: GoogleSansRegular
      fonts:
        - asset: assets/GoogleSansRegular.ttf
    - family: Agustina
      fonts:
        - asset: assets/fonts/Agustina.ttf
